name: "hacker_news_dbt"
version: "1.0.0"
config-version: 2

profile: "hacker_news_dbt"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

models:
  hacker_news_dbt:
    materialized: table

    activity_analytics:
      +schema: activity_analytics
      +meta:
        dagster:
          group: activity_analytics

seeds:
  quote_columns: false
